export default {
    EMAIL: /^[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*(\.[a-zA-Z]{2,})$/,
    MOBILENUMBER: /^[0-9]{8,12}$/,
    MOBILE_NUMBER: /^[0-9]{8,10}$/,
    MOBILENUMBERCOUNTRYCODE: /^\+[6-9][0-9]{8,12}$/,
    MOBILENUMBERWORLDCOUNTRYCODE: /^\+[1-9]\d{1,14}$/,
    MOBILENUMBERVALIDATION: /^[6-9][0-9]{9}$/,
    ONLY_NUMBER: /^[0-9]*$/,
    ALLOW_NUMERIC: /[^0-9]/g,
    OTP: /(\d{6})/,
    REMOVEHTMLTAG: /<\/?[^>]+(>|$)/gi,
    REMOVEHTMLSPACETAG: /nbsp;/g,
    YOUTUBE: /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#&?]*).*/,
    REMOVE_SPECIAL_CHAR: /[^\w ]/g,
    PAN_NUMBER: /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/,
    ONLY_CHARACTER: /^[A-Za-z]+$/,
    PIN_CODE: /^(\d{6})$/,
    NAMEWITHNUMBERS: /^[a-zA-Z 1-9]+$/,
    CITY: /^[A-Za-z\s\-']+$/,
    INDIAN_POSTAL_CODE: /^\d{6}$/,
    LETTERSANDSPACE: /^[A-Za-z\s]+$/,
    ACCOUNT_NUMBER: /^[0-9]{6,18}$/,
    NAME: /^[a-zA-Z. ]+$/,
    IFSC: /^[A-Z]{4}0[A-Z0-9]{6}$/,
    PERMITTED_ALPHANUMERIC: /^[a-zA-Z0-9_.%@]+$/,
    HTML_PATTERN: /<\/?[a-z][\s\S]*>/i,
    REMOVE_SPECIAL_CHARS: /[^a-zA-Z0-9 ,.]/g,
    NAME_CO_APPLICANT: /^[a-zA-Z-. ]+$/,
    EMAIL_COAPPLICANT: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
    MOBILE_NO_COAPPLICANT: /^\d{10}$/,
    NAME_COAPPLICANT_FILTER: /[^a-zA-Z-. ]/g,
    MIDDLE_NAME: /[^a-zA-Zà-öø-ÿĀ-žḀ-ỿ ]/g,
    INDIA_CODE: /^(\+91|91)/,
    SPACE_REMOVED: /\s+/g,
    MASK_DATA_NUM: /./g,
    MASK_EMAIL: /[^@]+/,
    TEN_NUMBER: /^[6-9]\d{9}$/,
    TEXT_NUMBER_SPLIT: /^(\d+)([A-Za-z]+)$/,
    MEM_MOBILE: /^\+?\d{10,14}$/,
    NUM_ONLY: /^\d+$/,
    TEXT_SPLIT: /\s+/,
    MULTIPLE_APARTMENT: /\b(Multiple|Multi) Apartments?\b/i,
    REFER_MOBILE: /^\+?\d{8,14}$/,
    ALLOW_MOBILE_CHARS: /^(\+?)(\d{6,15})$/,
    DATE_SUPERSCRIPT_REGEX: /^(\d+)([a-z]+)(.*)$/,
    ESCAPE_REGEX: /[.*+?^${}()|[\]\\]/g,
  };
  